//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Voting.Restful.API.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin()
        {
            this.AdminAssignments = new HashSet<AdminAssignment>();
        }
    
        public int AdminID { get; set; }
        public string AdminProfilePIc { get; set; }
        public string AdminName { get; set; }
        public string AdminPhoneNumber { get; set; }
        public string AdminEmail { get; set; }
        public int AdminZone { get; set; }
        public int AdminArea { get; set; }
        public string AdminAddressPresent { get; set; }
        public string AdminAddressPermanent { get; set; }
        public int UserID { get; set; }
        public string AdminGender { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual User User { get; set; }
        public virtual Zone Zone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminAssignment> AdminAssignments { get; set; }
    }
}
