//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Voting.Restful.API.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public int AnnoucemntID { get; set; }
        public string AnnoucementTitle { get; set; }
        public string AnoucementDetails { get; set; }
        public string AnnoucementImage { get; set; }
        public System.DateTime PublishedDate { get; set; }
    }
}
