//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Voting.Restful.API.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.AdminAssignments = new HashSet<AdminAssignment>();
        }
    
        public int AppointmentID { get; set; }
        public string AppointmentSubject { get; set; }
        public string AppointmentDetails { get; set; }
        public string UserPhoneNumber { get; set; }
        public string UserEmaul { get; set; }
        public Nullable<int> AssignToAdmin { get; set; }
        public Nullable<int> AssignmentUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminAssignment> AdminAssignments { get; set; }
    }
}
