//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Voting.Restful.API.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.ElectionCandidates = new HashSet<ElectionCandidate>();
        }
    
        public int CandidateID { get; set; }
        public string CandidateImage { get; set; }
        public string CandidateName { get; set; }
        public string CandidatePhoneNumber { get; set; }
        public string CandidateEmail { get; set; }
        public int CandidateZone { get; set; }
        public int CandidateArea { get; set; }
        public string CandidatePermanentAddress { get; set; }
        public string CandidatePresentAddress { get; set; }
        public string CandidateNID { get; set; }
        public Nullable<int> CandidateParty { get; set; }
        public int UserID { get; set; }
        public string CandidateGender { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Party Party { get; set; }
        public virtual User User { get; set; }
        public virtual Zone Zone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectionCandidate> ElectionCandidates { get; set; }
    }
}
