//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Voting.Restful.API.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectionAssignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ElectionAssignment()
        {
            this.ElectionCandidates = new HashSet<ElectionCandidate>();
        }
    
        public int ElectionAssignID { get; set; }
        public int ElectionID { get; set; }
        public int ZoneID { get; set; }
        public int AreaID { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Election_Detail Election_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectionCandidate> ElectionCandidates { get; set; }
        public virtual Zone Zone { get; set; }
    }
}
