//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Voting.Restful.API.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectionAssignmnet
    {
        public int AssignmentElection { get; set; }
        public Nullable<int> ElectionID { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ElectionStatus { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Election_Detail Election_Details { get; set; }
        public virtual Zone Zone { get; set; }
    }
}
