//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Voting.Restful.API.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voter()
        {
            this.Votes = new HashSet<Vote>();
        }
    
        public int VoterID { get; set; }
        public string VoterImage { get; set; }
        public string VoterName { get; set; }
        public string VoterPhoneNumber { get; set; }
        public string VoterEmail { get; set; }
        public int VoterZone { get; set; }
        public int VoterArea { get; set; }
        public string VoterPresentAddress { get; set; }
        public string VoterPermanentAddress { get; set; }
        public string VoterNID { get; set; }
        public int UserID { get; set; }
        public string VoterGender { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vote> Votes { get; set; }
        public virtual Zone Zone { get; set; }
    }
}
