//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Voting.Restful.API.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int VoteID { get; set; }
        public int ElectionID { get; set; }
        public int CandidateID { get; set; }
        public int VoterID { get; set; }
        public System.DateTime VoteDate { get; set; }
        public Nullable<int> AssignmentElectionID { get; set; }
    
        public virtual Election_Detail Election_Details { get; set; }
        public virtual ElectionAssignment ElectionAssignment { get; set; }
        public virtual Vote Vote1 { get; set; }
        public virtual Vote Vote2 { get; set; }
        public virtual Voter Voter { get; set; }
    }
}
